import React from 'react';
import { Button } from '@/components/ui/button';

const sol = value => (Number(value || 0) / 1e9).toLocaleString(undefined, { maximumFractionDigits: 9 });
export default function BuybackRecords({ rows, offset, onPage, loading }) {
  return <section className="mt-8 overflow-hidden rounded-2xl border border-border bg-card">
    <div className="border-b border-border p-5"><h2 className="font-heading font-semibold">Buyback history</h2><p className="mt-1 text-xs text-muted-foreground">Actual receipts are recorded only after finalization. Pending amounts are estimates.</p></div>
    {!rows.length ? <p className="p-8 text-center text-sm text-muted-foreground">No buybacks recorded on this page.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{['Date / status', 'Rewards collected', 'Buyback budget', 'Burn received', 'Transaction'].map(label => <th key={label} className="whitespace-nowrap p-4 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-t border-border"><td className="p-4"><p className="whitespace-nowrap">{new Date(row.createdAt).toLocaleString()}</p><p className={row.status === 'failed' ? 'mt-1 text-destructive' : 'mt-1 text-primary'}>{row.status}</p>{row.error && <p className="mt-1 max-w-xs text-destructive">{row.error}</p>}</td><td className="whitespace-nowrap p-4">{row.status === 'confirmed' ? `${sol(row.totalAccrued)} SOL` : 'Not finalized'}</td><td className="whitespace-nowrap p-4">{sol(row.sweptAmount)} SOL</td><td className="whitespace-nowrap p-4">{row.status === 'confirmed' ? (Number(row.coinsReceived || 0) / 10 ** (row.tokenDecimals || 0)).toLocaleString(undefined, { maximumFractionDigits: 6 }) : '—'}</td><td className="p-4"><a href={`https://solscan.io/tx/${row.signature}`} target="_blank" rel="noreferrer" className="text-primary underline">View transaction</a></td></tr>)}</tbody></table></div>}
    <div className="flex justify-between border-t border-border p-4"><Button variant="outline" size="sm" disabled={!offset || loading} onClick={() => onPage(Math.max(0, offset - 20))}>Previous</Button><Button variant="outline" size="sm" disabled={rows.length < 20 || loading} onClick={() => onPage(offset + 20)}>Next</Button></div>
  </section>;
}